### ISSUE TITLE
自荐来了

### ISSUE THREAD

**Issue by ekibun** [bangumi-data/awesome#1]
有一个[爬虫项目](https://github.com/ekibun/bangumi_onair)用上了你们的数据，效果的话是这样：
![Screenshot_2020-08-06-14-27-58-012_soko ekibun bangumi](https://user-images.githubusercontent.com/20966437/89498584-15bcb400-d7f1-11ea-971b-b908392f5d3e.jpg)

**Comment by ekibun** [comment]
不知道这种类型的算不算。可以的话希望bangumi-list能加上放送星期和时间的数据。

**Comment by weizhenye** [comment]
提 PR 呗，是用于 https://github.com/ekibun/Bangumi 的吧？可以直接写这个，按已有项的格式写就好了

**Comment by weizhenye** [comment]
大部分番剧的放送星期和时间可由 begin 计算得到。

一些例外情况正在 https://github.com/bangumi-data/bangumi-data/issues/106 讨论，会从数据格式上支持计算出正确的信息。
